-- DROP DATABASE IF EXISTS trtpo_system;

CREATE DATABASE IBAStudentsHelper DEFAULT CHARACTER SET 'utf8';

USE IBAStudentsHelper;

CREATE TABLE Users(
USER VARCHAR(100),
PASSWORD VARCHAR(100),
ROLE VARCHAR(20)
);

CREATE TABLE Groups(
GROUP_NUMBER VARCHAR(20),
AVG_MARK DOUBLE, 
PRIMARY KEY(GROUP_NUMBER)
);


CREATE TABLE Students(
ID INTEGER AUTO_INCREMENT,
FIRST_NAME VARCHAR(100),
SECOND_NAME VARCHAR(100),
AVG_MARK DOUBLE,
GROUP_NUMBER VARCHAR(20) NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY (GROUP_NUMBER) REFERENCES Groups(GROUP_NUMBER)
);

CREATE TABLE Professors(
ID INTEGER AUTO_INCREMENT,
FIRST_NAME VARCHAR(100),
SECOND_NAME VARCHAR(100),
FATHER_NAME VARCHAR(100),
BIRTH_DATE VARCHAR(20),
AVG_MARK DOUBLE,
PRIMARY KEY(ID)
);

CREATE TABLE Studies(
ID INTEGER AUTO_INCREMENT,
NAME VARCHAR(20),
HOURS INTEGER,
PROFESSOR_ID INTEGER NOT NULL,
AVG_MARK DOUBLE,
PRIMARY KEY(ID),
FOREIGN KEY (PROFESSOR_ID) REFERENCES Professors(ID)
);

CREATE TABLE Marks(
ID INTEGER AUTO_INCREMENT,
STUDY_ID INTEGER NOT NULL,
STUDENT_ID INTEGER NOT NULL,
DATE VARCHAR(20),
PROFESSOR_ID INTEGER NOT NULL,
MARK INTEGER, 
COMMENTS VARCHAR(20),
PRIMARY KEY(ID),
FOREIGN KEY(STUDY_ID) REFERENCES Studies(ID),
FOREIGN KEY(STUDENT_ID) REFERENCES Students(ID),
FOREIGN KEY(PROFESSOR_ID) REFERENCES Professors(ID)
);

